### ISSUE TITLE
Link Issues

### ISSUE THREAD

**Issue by mody7860** [colbylwilliams/Xamarin.TTTAttributedLabel#2]
After you add the component and try building, you get the following error - 
Error MT2002: Failed to resolve "System.Void ObjCRuntime.DelegateProxyAttribute::.ctor(System.Type)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" (MT2002)

**Comment by colbylwilliams** [comment]
I'd recommend using the [NuGet package](https://www.nuget.org/packages/Xamarin.TTTAttributedLabel) instead of the Component.  Can you try using NuGet and let me know if it solves the issue?

**Comment by mody7860** [comment]
Thanks for getting back Colby.  I tried a different approach.  Used
Textview via a custom renderer.

**Comment by colbylwilliams** [comment]
Glad you got past the issue @mody7860.  Happy coding
