### ISSUE TITLE
 Uploading application to App Store

### ISSUE THREAD

**Issue by galdanay** [colbylwilliams/Xamarin.TTTAttributedLabel#3]
when trying to upload my app to the App store i got the error:
ERROR ITMS-90668: "Invalid Bundle Executable. The executable file '[projectName]/Frameworks/TTTAttributedLabel.framework/TTTAttributedLabel' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by mzekrallah** [comment]
@colbylwilliams @galdanay I also had the same problem today ! any help guys ? how to workaround this ? the error appears only when uploading to AppStore through Application Loader.

**Comment by colbylwilliams** [comment]
thanks @galdanay, @mzekrallah looking into it now

**Comment by royvou** [comment]
Changing the native xcode projects options and disable bitcode seems a quick workaround @colbylwilliams.

(worked for me)

Unfortunately i don't have a mac available to submit a PR now :(

**Comment by colbylwilliams** [comment]
@galdanay, @mzekrallah, @royvou 

[Version 2.0.0.1](https://www.nuget.org/packages/Xamarin.TTTAttributedLabel/2.0.0.1) should resolve the issue.  Please let me know if it does not.
