### ISSUE TITLE
App crash - deny-mmap mapped file has no team identifier and is not a platform binary

### ISSUE THREAD

**Issue by danmkent** [colbylwilliams/Xamarin.TTTAttributedLabel#4]
After adding the binding to our Xamarin.iOS project, our app crashes when running a release build signed using an enterprise certificate. 

The log has the following:

<Notice>: AMFI: MhubAppiOS(pid 1960) - deny-mmap mapped file has no team identifier and is not a platform binary: /private/var/mobile/Containers/Bundle/Application/373AAF1D-AA79-41BE-AD29-C3E85C9338AE/MhubAppiOS.app/Frameworks/TTTAttributedLabel.framework/TTTAttributedLabel

Any idea what could cause this?

**Comment by colbylwilliams** [comment]
@danmkent could you try updating to [Version 2.0.0.1](https://www.nuget.org/packages/Xamarin.TTTAttributedLabel/2.0.0.1) and let me know if it resolves your issue?

**Comment by danmkent** [comment]
@colbylwilliams We found the cause of the issue - the enterprise certificate in question did not have a Organisational Unit attribute, which apparently can cause this error when some libraries are included in the build.

Generating a new enterprise certificate and provisioning profile resolved the issue.

**Comment by colbylwilliams** [comment]
Cool.  Thanks for letting me know @danmkent
