### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by danmkent** [colbylwilliams/Xamarin.TTTAttributedLabel#5]
I'm trying to build the bindings but I'm getting this error after running make in the extern folder:

Users/programming/mhubdev/Xamarin.TTTAttributedLabel-master/extern/Release-binding/ApiDefinitions.cs(65,12): error CS0101: The namespace `Xamarin.TTTAttributedLabel' already contains a definition for`TTTAttributedLabel'
        /Users/programming/mhubdev/Xamarin.TTTAttributedLabel-master/extern/Release-binding/ApiDefinitions.cs(54,12): (Location of the symbol related to previous error)
        btouch: API binding contains errors.

What do I need to do in order to be able to build the bindings?

**Comment by colbylwilliams** [comment]
The `ApiDefinitions.cs` file requires some tweaks after it's generated by ObjectiveSharpie.  I've committed the "tweaked" version and updated the `Makefile` to use the version in the repo instead of ObjectiveSharpie.  Get latest an you should be able to build.
