### ISSUE TITLE
ERROR ITMS-90668: Invalid Bundle Executable.

### ISSUE THREAD

**Issue by samsmith16** [colbylwilliams/Xamarin.TTTAttributedLabel#8]
Hi,

I'm using NuGet package 2.0.0.1 and still seeing this issue while submitting to iTunesConnect:

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'My.app/Frameworks/TTTAttributedLabel.framework/TTTAttributedLabel' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by fluffyclaret** [comment]
Any update on this? I'm seeing exactly the same issue (via the Component Store - version 2.0.0).

Please help.

**Comment by fluffyclaret** [comment]
Sorted it. The XCode project had 'Enable BitCode' => 'YES' in the Build Settings. I switched this and rebuilt the project.

**Comment by colbylwilliams** [comment]
Fixed in version [2.0.0.2](https://www.nuget.org/packages/Xamarin.TTTAttributedLabel/2.0.0.2).

**Comment by JulianPasque** [comment]
I still get this error in 2.0.02

**Comment by nmilcoff** [comment]
I had this issue with 2.0.0.2, but updating to latest version on VS4Mac + nuking bin/obj solved it.
